server: 
  port: 9003
spring: 
  application:  
    name: tensquare-qa #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.40.134:3306/tensquare_qa?characterEncoding=UTF8
    username: root
    password: 123456
  jpa: 
    database: MySQL
    show-sql: true
#自定义属性jwt相关
jwt:
  config:
    key: itcast
eureka:
  client:
    #Eureka服务的地址
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    #用于表示在猜测主机名时，服务器的IP地址应该与操作系统报告的主机名相对应。(注册服务和客户端如果在一台机器上则无需配置)
    prefer-ip-address: true
feign:
  #熔断器配置
  hystrix:
    #开启熔断器
    enabled: true